name: Deploy MERN App to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: sit727-24t1-jarjana-f2b2922
      GKE_CLUSTER: autopilot-cluster-1
      GKE_ZONE: australia-southeast1
      K8S_NAMESPACE: default
      FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/stories-frontend
      BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/stories-backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Build and push backend image
      run: |
        cd ./server
        docker build -t ${{ env.BACKEND_IMAGE }}:1 .
        docker push ${{ env.BACKEND_IMAGE }}:1
        
    - name: Build and push frontend image
      run: |
        cd ./client
        docker build -t ${{ env.FRONTEND_IMAGE }}:1 .
        docker push ${{ env.FRONTEND_IMAGE }}:1
     
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
        echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV
    
    - name: Get GKE credentials
      run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }} --project ${{ env.PROJECT_ID }}

    - name: Deploy with Helm
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm upgrade --install stories-mongo --set auth.enabled=false,arbiter.enabled=false,architecture=replicaset,replicaSet.replicas.secondary=1 bitnami/mongodb
        helm upgrade --install stories-backend ./helm-charts/backend
        helm upgrade --install stories-frontend ./helm-charts/frontend
