name: Deploy MERN Stack to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: sit727-24t1-jarjana-f2b2922
      GKE_CLUSTER: autopilot-cluster-1
      GKE_ZONE: australia-southeast1
      K8S_NAMESPACE: default

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Deploy with Helm
      run: |
        helm upgrade --install backend ./helm-charts/backend \
        helm upgrade --install frontend ./helm-charts/frontend \
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm upgrade --install stories-mongo --set auth.enabled=false,architecture=replicaSet,service.type=LoadBalancer,replicaSet.replicas.secondary=1 bitnami/mongodb
        helm upgrade --install stories-prometheus bitnami/prometheus
        helm upgrade --install stories-grafana bitnami/grafana
